"""Gainr-owned normalized source schemas and table defaults."""

from __future__ import annotations

from analytics_service.source_schema import DatasetSpec

ADS_COLUMNS = (
    "id",
    "user_id",
    "category_type",
    "parent_id",
    "category_id",
    "title",
    "rental_duration",
    "rental_fee",
    "is_rent_negotiable",
    "city_id",
    "locality_id",
    "photos",
    "total_favorite",
    "total_like",
    "user_contact_view_count",
    "user_viewed_count",
    "actual_view_count",
    "status",
    "keywords",
    "top_start_date",
    "top_end_date",
    "premium_start_date",
    "premium_end_date",
    "created_at",
    "deleted_at",
    "description",
)

USER_COLUMNS = (
    "id",
    "state_id",
    "city_id",
    "gender",
    "platform",
    "device_platform",
    "role",
    "is_verified",
    "status",
    "created_at",
    "updated_at",
    "user_type",
    "deleted_at",
)

GAINR_DATASET_SPECS: dict[str, DatasetSpec] = {
    "search_history": DatasetSpec(
        "semantic_search_history.csv",
        ("id", "request_id", "query_text", "created_at"),
        usecols=("id", "request_id", "query_text", "created_at"),
        numeric_columns=("id",),
        timestamps_are_utc=True,
        history_window=True,
    ),
    "api_usage": DatasetSpec(
        "semantic_search_api_usage.csv",
        (
            "id",
            "request_id",
            "execution_path",
            "result_count",
            "total_results",
            "status",
            "duration_ms",
            "attempts_json",
            "plan_cache_hit",
            "result_cache_hit",
            "timings_json",
            "context_json",
            "created_at",
        ),
        usecols=(
            "id",
            "request_id",
            "company_id",
            "execution_path",
            "result_count",
            "total_results",
            "status",
            "api_call_count",
            "input_tokens",
            "output_tokens",
            "thought_tokens",
            "total_tokens",
            "duration_ms",
            "attempts_json",
            "plan_cache_hit",
            "result_cache_hit",
            "timings_json",
            "context_json",
            "created_at",
        ),
        numeric_columns=(
            "id",
            "result_count",
            "total_results",
            "api_call_count",
            "input_tokens",
            "output_tokens",
            "thought_tokens",
            "total_tokens",
            "duration_ms",
        ),
        database="telemetry",
        timestamps_are_utc=True,
        history_window=True,
    ),
    "categories": DatasetSpec(
        "categories.csv",
        ("id", "name", "cat_group"),
        usecols=("id", "name", "cat_group"),
        numeric_columns=("id", "cat_group"),
    ),
    "sub_categories": DatasetSpec(
        "sub_categories.csv",
        ("id", "categoryId", "name"),
        usecols=("id", "categoryId", "name"),
        numeric_columns=("id", "categoryId"),
    ),
    "states": DatasetSpec(
        "states.csv",
        ("id", "name"),
        usecols=("id", "name"),
        numeric_columns=("id",),
    ),
    "location": DatasetSpec(
        "location.csv",
        ("id", "city", "state_id", "price"),
        usecols=("id", "city", "state_id", "price"),
        numeric_columns=("id", "state_id", "price"),
    ),
    "attributes": DatasetSpec(
        "attributes.csv",
        ("id", "name"),
        usecols=("id", "name"),
        numeric_columns=("id",),
    ),
    "attribute_values": DatasetSpec(
        "attribute_values.csv",
        ("id", "attributeId", "value"),
        usecols=("id", "attributeId", "value"),
        numeric_columns=("id", "attributeId"),
    ),
    "ads_attributes": DatasetSpec(
        "ads_attributes.csv",
        ("ads_id", "attribute_id", "value"),
        usecols=("ads_id", "attribute_id", "value"),
        numeric_columns=("ads_id", "attribute_id"),
    ),
    "ads": DatasetSpec(
        "ads.csv",
        ("id", "user_id", "category_id", "title", "created_at"),
        usecols=ADS_COLUMNS,
        dtypes={"status": "str"},
        numeric_columns=(
            "id",
            "user_id",
            "category_type",
            "parent_id",
            "category_id",
            "rental_fee",
            "is_rent_negotiable",
            "city_id",
            "locality_id",
            "total_favorite",
            "total_like",
            "user_contact_view_count",
            "user_viewed_count",
            "actual_view_count",
        ),
    ),
    "users": DatasetSpec(
        "users.csv",
        ("id", "state_id", "city_id", "created_at"),
        usecols=USER_COLUMNS,
        numeric_columns=(
            "id",
            "state_id",
            "city_id",
            "gender",
            "platform",
            "is_verified",
            "user_type",
        ),
    ),
}

GAINR_DEFAULT_TABLES = {
    "search_history": "semantic_search_history",
    "api_usage": "semantic_search_api_usage",
    "categories": "categories",
    "sub_categories": "sub_categories",
    "states": "states",
    "location": "location",
    "attributes": "attributes",
    "attribute_values": "attribute_values",
    "ads_attributes": "ads_attributes",
    "ads": "ads",
    "users": "users",
}
